### ISSUE TITLE
Services Tab.

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#18]
Freight Forwarding: Thumbnail Picture Change will share with you.
Terminal & Shipping:  Thumbnail Picture Change - take Terminal Picture from Main Slider.
Logistics: Thumbnail Picture Change will share with you.

**Comment by radean** [comment]
ok, will change when get response.

**Comment by ayazvayani** [comment]
Freight Forwarding: Thumbnail Picture Change - Placed in sharing Folder.
Terminal & Shipping: Thumbnail Picture Change - take Terminal Picture from Main Slider.
Logistics: Thumbnail Picture Change - Placed in sharing Folder - Truck-1
Warehouse Thumbnail Picture Change:  Thumbnail Picture Change - Placed in sharing Folder.

**Comment by radean** [comment]
Ok will be good in 0.3 version.

**Comment by ayazvayani** [comment]
Service Thumbnail picture update in sharing folder change pictures which is in folder. remaining will be same.

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
freight forwarding picture not update.

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
can you place updated pictures for my review

**Comment by radean** [comment]
Done
