### ISSUE TITLE
About Us.

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#20]
Text Align Justify according to web page area.

**Comment by radean** [comment]
Will be good in next push

**Comment by ayazvayani** [comment]
Remove - Readmore button

**Comment by ayazvayani** [comment]
when i click on about me from menu bar (about me heading should show.

**Comment by radean** [comment]
About us button is working and Service Card Headings are also working, from now on

**Comment by ayazvayani** [comment]
Remove - Readmore button
font colors are different

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
Remove - Readmore button
font colors are different

**Comment by radean** [comment]
Fixed
