### ISSUE TITLE
Text Modification

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#21]
Paragraph text will be little bit darker as readable
also it should be align justify.

**Comment by radean** [comment]
Done, will be good in 0.3. you can see the version of website on line after footer

**Comment by radean** [comment]
if you can tell me where it is not justified.

**Comment by ayazvayani** [comment]
Text align Required Following:
1. Thumbnail Text of Services
2. Service/warehouse & Storage Page
3. Service/air freight Page
4. Service/Trading Page
5. Branches/Canada - sea freight paragraph
6. Branches/UAE - Service & Logistic paragraph

**Comment by radean** [comment]
Done .Recheck if any error errupt.

**Comment by ayazvayani** [comment]
Text align Required Following:

Thumbnail Text of Services - Not Update
Service/air freight Page - Not Update
Team / what we do / (our mission , our goals & about absa Group

these text need to align

**Comment by radean** [comment]
Done
