### ISSUE TITLE
About us Image Slider

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#22]
Add Pictures of Offices
add some pictures from jabel ali
you can take pictures from sharing location folder as jabel ali slider folder

**Comment by radean** [comment]
ok it will be good if you select & share images.

**Comment by ayazvayani** [comment]
Add Pictures
Sudan Office
Some Pictures from jabel ali
some terminal picture of ABSA placed in folder

**Comment by radean** [comment]
Only 6 images can be place there!

**Comment by ayazvayani** [comment]
will place folder in shared folder

**Comment by ayazvayani** [comment]
You can take pictures from ABSA Sliders Folder from Sharing

**Comment by radean** [comment]
Done placing.
