### ISSUE TITLE
add new row

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#25]
add new row for office location.
location file will be available on sharing folder. once it approved.

**Comment by radean** [comment]
Ok its done i added a new stripe under counter stripe.

**Comment by radean** [comment]
i will put all addresses after its approved.

**Comment by ayazvayani** [comment]
Addressess File Update in folder "Final List Office.docx"
once it done and approved then remove alll addresses from branches page. after my goahead.

**Comment by ayazvayani** [comment]
Addresses Revised File Update in folder "Final List Office - Revised"
Remove all addresses from branches page.

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
just mention contry remove ciyt

for example
ABSA Iraq
Basra – IRAQ.

remove basra
same applied on canada
and Saudia also
little bit text dark on all these fields only
for any query feel free ask.

**Comment by radean** [comment]
Done as told.

**Comment by ayazvayani** [comment]
Please Recheck
City Remove - Not Updated
on Saudia add germany add mention please check

**Comment by radean** [comment]
Kindly point out problem
