### ISSUE TITLE
Terminal Storage - Page.

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#30]
Remove the video bottom table of Our Facilty
add picture slider instead of that video
Picture will take from shred folder dubai and jabel terminal

go on down on same page
you put text and pictures of JUBAIL TERMINAL
Current Position: Picture Slider on Left and text on Right ( Need to Swap)
New Position: Picture Slider on Right and Text on Left.

**Comment by radean** [comment]
Need Pictures

**Comment by ayazvayani** [comment]
in progress

**Comment by ayazvayani** [comment]
You can take pictures from ABSA Sliders Folder from Sharing

**Comment by radean** [comment]
Done
