### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#32]
Footer Bar (Changes)

Remove Social Icons
Our Support Text replace with office timings
and remove 24hour support lines
time will be same.

on Side Address Box (Changes)
Location Replace with Head Office
Add Fax: 00966-13-8341182
Saudi Arabia Replace with Kingdom of Saudi Arabia.

Form:
form fill data emailed to absa@absaco.com

**Comment by radean** [comment]
I will make Form At the end of dev log

**Comment by radean** [comment]
Done
