### ISSUE TITLE
Tour and Travel - Page

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#33]
I will create a folder in shared folder by name of travel and tour

need picture slider on blank right area

**Comment by radean** [comment]
Make a folder please

**Comment by ayazvayani** [comment]
in progress

**Comment by ayazvayani** [comment]
You can take pictures from ABSA Sliders Folder from Sharing

**Comment by radean** [comment]
Added with six randomly selected pictures.

**Comment by ayazvayani** [comment]
coverpage on both version web and mobile version me thora uper kar dena bando ka face uper ajaye.

**Comment by radean** [comment]
Resolved
