### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#4]
Canada, INdia, Jedda, dammam, dubai port ki picture use kar saktay he app
Colorfull port Picture
website ko lively show karna he
modern
back me jo ship ka bht achi pic the lekin kisi or ka he. ap evergreen ka use kar saktay he.

**Comment by radean** [comment]
ok it will take a little time in making a picture collection

**Comment by radean** [comment]
Try to get the pictures.
