### ISSUE TITLE
Transportation Page

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#46]
Same Header Pic issue as shipping may be its on all headers
Text needs to align justify
same issue for table figure totally not understandable

**Comment by radean** [comment]
I added a Scroll on this table. tell me where are more of them to fix.

**Comment by ayazvayani** [comment]
table not scrolling

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
Thumbnail Picture update - remove Absa Logo. place in folder.

**Comment by radean** [comment]
done
