### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#51]
Footer Slide address change to Head Office Damam details.

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
As discussed: worked on footer which was suitable for you:

Option 1: remove map and bottom text 4 fields adjusted on Map Area.
Option-2 Create footer for all pages.

If Option -2: will provide all offices pins and once it done so form drop down menu will remove and email send auto on respective email ids.

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
Add Japan on form drop down. and Singapore missing.,

**Comment by ayazvayani** [comment]
recheck pin of maps, call me at your desk when you will doing this.

**Comment by radean** [comment]
Added
Done
