### ISSUE TITLE
Address Tabs.

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#58]
MODERN MARITIME LOGISTICS - Remove all Email addresses
MODERN FREIGHT LOGISTICS: Remove email from Jeddah and riyadh
EXPERT MARITIME SERVICES:

DUBAI: travel.ae@absaco.com replace with g.canute@absaco.com

Singapore box update:
Al-Barrak Singapore Intl Pte Ltd
10, Anson Road #10-18 International Plaza
Phone   : +65-62252010
Fax       : +65-62252197
Mobile  : +65-93868084
Singapore

Canada
E-Mail : zain@absaco.com change to E-Mail : nick@absaco.com

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
Correction:

MODERN MARITIME LOGISTICS - Remove all Email addresses
MODERN FREIGHT LOGISTICS: Remove email from Jeddah and riyadh

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
add flags on address thumbnails.
add japan address

**Comment by radean** [comment]
done
