### ISSUE TITLE
Team Page.

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#60]
Basem Sabri Bakhurji	Administrative & Customs Clearance Manage 
Replace Designation
General HR & Admin Manager

Faraj Hawsse	Marketing Manager – Evergreen K.S.A 
Replace Designation
General Manager Marketing – Evergreen K.S.A

Remove: Saji Alexander	Information & Technology – Dammam

all GM below group director

**Comment by ayazvayani** [comment]
Add Memeber in on Team

Akshay Anand  - General Manager Finance & Business Development

**Comment by radean** [comment]
done
