### ISSUE TITLE
Live Chat.

### ISSUE THREAD

**Issue by ayazvayani** [radean/al-barrak-webapp#64]
https://purechat.com/support/how-to-add-live-chat-to-website#

as discussed addition of new element on website
Make any email ID

notification of msgs, green button when some one online
when offline alert via email

workable on phones.

for any query and confusion feel free to ask.

**Comment by radean** [comment]
Need Email Address
I will use tawk.to

**Comment by ayazvayani** [comment]
Email: absacochat@gmail.com
PW: sanadeem786

**Comment by ayazvayani** [comment]
Email: absacoagent1@gmail.com
PW: sanadeem786
